# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qr.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(201, 201)
        MainWindow.setMinimumSize(QtCore.QSize(201, 201))
        MainWindow.setMaximumSize(QtCore.QSize(201, 201))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 201, 201))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.toolButton_2 = QtWidgets.QToolButton(self.tab)
        self.toolButton_2.setGeometry(QtCore.QRect(170, 0, 25, 25))
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolBox = QtWidgets.QToolBox(self.tab)
        self.toolBox.setGeometry(QtCore.QRect(0, 0, 181, 161))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 181, 65))
        self.page.setObjectName("page")
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 161, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 181, 65))
        self.page_2.setObjectName("page_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 20, 171, 26))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 181, 65))
        self.page_3.setObjectName("page_3")
        self.toolButton = QtWidgets.QToolButton(self.page_3)
        self.toolButton.setGeometry(QtCore.QRect(10, 20, 25, 25))
        self.toolButton.setObjectName("toolButton")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 111, 18))
        self.label_2.setObjectName("label_2")
        self.toolBox.addItem(self.page_3, "")
        self.toolBox.raise_()
        self.toolButton_2.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_3.setGeometry(QtCore.QRect(170, 0, 25, 25))
        self.toolButton_3.setObjectName("toolButton_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(0, 0, 161, 26))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 131, 131))
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setLineWidth(1)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QR-generate"))
        self.toolButton_2.setToolTip(_translate("MainWindow", "Generate"))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "text"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "url"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "filename"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "GEN"))
        self.toolButton_3.setToolTip(_translate("MainWindow", "Save"))
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.lineEdit_3.setToolTip(_translate("MainWindow", "Name code"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "OUT"))
